// NO-CARRIER(预备停用)：手动 node verify.mjs <playwright路径>，不注册自动hooks。
// 5秒状态锚点：运行结束打印PASS或非零退出；退出条件：工具移除时删除本测试。
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {loadSource} from '../../../server.mjs';
import * as model from './candidate-model.mjs';
import {legacyCandidateFixture} from '../../../test-fixtures.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.argv[2]);
const source=await loadSource(),identity=Object.fromEntries(['chartPath','audioPath','chartSha256','audioSha256'].map(k=>[k,source[k]]));
const envelope=chart=>({format:model.DRAFT_FORMAT,version:2,status:'unreviewed-draft',createdAt:new Date().toISOString(),source:identity,review:{voice:'',reason:''},timing:model.timing,chart,differences:model.differences(source.chart,chart)});
const id='review-00000000-0000-4000-8000-000000000001',tap={id,lane:0,timeMs:0,type:0,durationMs:0};
let chart=model.clone(source.chart);chart.notes.push(tap);assert.equal(model.validateDraft(envelope(chart),source).chart.notes.length,57);
for(const mutate of [c=>c.notes.push({...tap}),c=>c.notes.at(-1).id='legacy-fake',c=>c.notes.at(-1).timeMs=-1,c=>c.notes.at(-1).timeMs=40000,c=>c.notes.at(-1).timeMs=source.chart.notes[0].timeMs,c=>{c.notes.at(-1).type=1;c.notes.at(-1).durationMs=20;},c=>c.notes[0].lane=3]){const bad=model.clone(chart);mutate(bad);assert.throws(()=>model.validateDraft(envelope(bad),source));}
const wrong=envelope(chart);wrong.source={...identity,chartSha256:'0'.repeat(64)};assert.throws(()=>model.validateDraft(wrong,source));
const empty=model.clone(source.chart);empty.notes=[];assert.equal(model.validateDraft(envelope(empty),source).differences.length,56);
const held=model.clone(source.chart);held.notes[0]={...held.notes[0],timeMs:0,type:1,durationMs:1000};held.notes.push({...tap,timeMs:500});assert.throws(()=>model.validateChart(held));
const old=legacyCandidateFixture(source);
assert.equal(model.validateCandidate(old,source).version,2);assert.equal(model.validateCandidate(old,source).review.reason,old.review.reason);
const oldDraft={...model.clone(old),format:model.DRAFT_FORMAT,status:'unreviewed-draft',createdAt:new Date().toISOString(),review:{voice:'',reason:''}};assert.equal(model.validateDraft(oldDraft,source).version,2);
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1800,height:1600},acceptDownloads:true}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const click=id=>page.locator('#'+id).click(),select=id=>page.locator('#note').selectOption(id),count=()=>page.locator('#note option').count();
const ready=()=>page.waitForFunction(()=>document.querySelector('#load').textContent.includes('原谱已加载'));
const playing=()=>page.waitForFunction(()=>document.querySelector('#play').textContent==='暂停');
const seek=async t=>page.locator('#seek').evaluate((el,value)=>{el.value=String(value);el.dispatchEvent(new Event('input'));},t);
async function download(button){const pending=page.waitForEvent('download');await click(button);const d=await pending;return JSON.parse(await readFile(await d.path(),'utf8'));}
async function upload(body){await page.locator('#import').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(body))});await page.waitForFunction(()=>document.querySelector('#import').value==='');}
try{
 await page.goto('http://127.0.0.1:8769');await ready();assert.equal(await count(),57);assert.match(await page.locator('#hash').textContent(),new RegExp(source.chartSha256));
 await seek(0);await click('addCurrent');const added=await page.locator('#note').inputValue();assert.match(added,model.addedIdPattern);assert.equal(await count(),58);assert.equal(await page.locator('#time').inputValue(),'0');
 await page.locator('#noteClick').check();await page.locator('#beatClick').check();await click('audition');await playing();assert.equal(await page.locator('#loop').isChecked(),true);await page.locator('#mode').selectOption('original');await page.locator('#mode').selectOption('candidate');await click('exitLoop');assert.equal(await page.locator('#playRange').inputValue(),'full');await click('playFull');await playing();await page.waitForFunction(()=>Number(document.querySelector('#seek').value)>.05);await click('stopPlayback');
 await click('deleteNote');assert.equal(await count(),57);await click('undo');assert.equal(await page.locator('#note').inputValue(),added);assert.equal(await count(),58);await click('redo');assert.equal(await count(),57);await click('undo');assert.equal(await page.locator('#note').inputValue(),added);
 await select('legacy-27');await click('deleteNote');assert.equal(await page.locator('#note').inputValue(),'legacy-28');assert.match(await page.locator('#diff').textContent(),/remove legacy-27/);await click('undo');assert.equal(await page.locator('#note').inputValue(),'legacy-27');await click('redo');await click('undo');
 await select('legacy-13');await page.locator('#time').fill('9562');await click('apply');assert.match(await page.locator('#diff').textContent(),/move legacy-13/);await select('legacy-27');await click('deleteNote');
 await click('saveDraft');await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('已保存本地草稿'));
 // A competing isolated tab writes the same draft; stale writes must be rejected.
 const other=await context.newPage();other.on('dialog',d=>d.accept());other.on('pageerror',e=>errors.push(e.message));await other.goto('http://127.0.0.1:8769');await other.waitForFunction(()=>document.querySelector('#load').textContent.includes('原谱已加载'));await other.locator('#resumeSaved').click();await other.locator('#restorePrompt').waitFor({state:'hidden'});await other.locator('#note').selectOption(added);await other.locator('[data-step="10"]').click();await other.locator('#saveDraft').click();await other.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('已保存本地草稿'));await page.locator('#conflict').waitFor({state:'visible'});
 const remote=await page.evaluate(()=>localStorage.getItem(Object.keys(localStorage).find(k=>k.endsWith(':main'))));await click('saveDraft');await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('其他页面更新'));assert.equal(await page.evaluate(()=>localStorage.getItem(Object.keys(localStorage).find(k=>k.endsWith(':main')))),remote);await click('loadRemote');await page.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('已恢复本地草稿'));await other.close();
 const draft=await download('downloadDraft');model.validateDraft(draft,source);assert.equal(draft.version,2);assert.deepEqual(draft.differences.map(d=>d.operation).sort(),['add','move','remove']);assert.ok(draft.chart.notes.some(n=>n.id===added));
 await page.reload();await ready();await page.locator('#restorePrompt').waitFor({state:'visible'});await click('resumeSaved');await page.locator('#restorePrompt').waitFor({state:'hidden'});assert.equal(await count(),57);assert.ok(await page.locator('#note option').evaluateAll((options,id)=>options.some(o=>o.value===id),added));assert.match(await page.locator('#diff').textContent(),/remove legacy-27/);
 // Complete strict export and reimport, retaining the generated UUID and review provenance.
 await page.locator('details').filter({has:page.locator('#voice')}).locator('summary').click();await page.locator('#voice').selectOption('melody');await page.locator('#reason').fill('未审核自动测试：仅验证新增删除工具导出，不表示音乐对齐。');const candidate=await download('export');model.validateCandidate(candidate,source);assert.equal(candidate.status,'unapproved-candidate');assert.deepEqual(candidate.chart,draft.chart);await select(added);await click('deleteNote');await upload(candidate);const importedSelection=await page.locator('#note').inputValue();assert.equal(await page.locator('#time').inputValue(),String(candidate.chart.notes.find(n=>n.id===importedSelection)?.timeMs));assert.ok(await page.locator('#note option').evaluateAll((options,id)=>options.some(o=>o.value===id),added));
 // Explicit add controls reject out-of-range and overlapping judgement windows without mutation.
 const beforeInvalid=await count();await page.locator('#addTime').fill('40000');await click('addAtTime');assert.match(await page.locator('#editStatus').textContent(),/40s/);assert.equal(await count(),beforeInvalid);
 await page.locator('#addTime').fill('870');await click('addAtTime');assert.match(await page.locator('#editStatus').textContent(),/冲突/);assert.equal(await count(),beforeInvalid);
 await page.locator('#addLane').selectOption('1');await page.locator('#addTime').fill('1000');await click('addAtTime');const second=await page.locator('#note').inputValue();assert.notEqual(second,added);assert.equal(await count(),beforeInvalid+1);
 await page.locator('#addTime').focus();await page.keyboard.press('BracketRight');await page.keyboard.press('Control+z');await page.keyboard.press('Delete');assert.equal(await count(),beforeInvalid+1);await page.locator('#reason').focus();await page.keyboard.press('BracketRight');assert.equal(await page.locator('#time').inputValue(),'1000');
 // Physical pointer add, then physical drag with add mode off.
 await click('all');await page.locator('#addMode').check();await page.locator('#timeline').scrollIntoViewIfNeeded();let box=await page.locator('#timeline').boundingBox();const dimensions=await page.locator('#timeline').evaluate(el=>({w:el.width,h:el.height}));await page.mouse.click(box.x+box.width*.25,box.y+box.height*235/dimensions.h);const clicked=await page.locator('#note').inputValue();assert.match(clicked,model.addedIdPattern);assert.equal(await page.locator('#time').inputValue(),'10000');
 await page.locator('#addMode').uncheck();box=await page.locator('#timeline').boundingBox();await page.mouse.move(box.x+box.width*.25,box.y+box.height*240/dimensions.h);await page.mouse.down();await page.mouse.move(box.x+box.width*.2525,box.y+box.height*240/dimensions.h);await page.mouse.up();assert.ok(Math.abs(Number(await page.locator('#time').inputValue())-10100)<=1);
 await click('audition');await playing();await click('playFull');await playing();assert.equal(await page.locator('#playRange').inputValue(),'full');assert.equal(await page.locator('#loop').isChecked(),false);await click('stopPlayback');
 const moved=await download('downloadDraft');model.validateDraft(moved,source);assert.equal(moved.chart.notes.find(n=>n.id===clicked).lane,3);assert.equal(moved.chart.notes.find(n=>n.id===second).timeMs,1000);
 await upload(old);assert.equal(await count(),57);assert.equal(await page.locator('#voice').inputValue(),'melody');assert.equal(await page.locator('#reason').inputValue(),old.review.reason);assert.match(await page.locator('#saveStatus').textContent(),/v1/);const migrated=await download('downloadDraft');assert.equal(migrated.version,2);assert.deepEqual(migrated.chart,old.chart);assert.equal(migrated.review.reason,old.review.reason);
 await upload(oldDraft);assert.equal(await page.locator('#reason').inputValue(),'');assert.equal(await count(),57);
 const after=await loadSource();assert.equal(after.chartSha256,source.chartSha256);assert.equal(after.audioSha256,source.audioSha256);assert.deepEqual(errors,[]);
 console.log('PASS schema v2 + legacy v1 migration; add/audition/AB/save/reload/export/reimport; delete/undo/redo IDs and selection; move/remove/add diff; competing-tab stale write rejected; invalid range/window/Hold/hash/ID; input hotkeys; physical add/drag; full-note regression; original hashes unchanged; pageErrors=0');
}finally{await browser.close();}
